host: enershare.epu.ntua.gr

coreContainer:
  secrets:
    idsIdentity:
      name: ids-consumer-secret
  image: docker.nexus.dataspac.es/core-container:1.3.0
  ingress:
    path: /ntua-consumer/(.*)
    rewriteTarget: /$1
    clusterIssuer: letsencrypt
    ingressClass: public
  environment:
    - name: ENABLE_OCSP
      value: "false"
    - name: ENABLE_CRL
      value: "false"

adminUi:
  enabled: true
  image: docker.nexus.dataspac.es/ui/core-container-ui:master
  ingress:
    path: /ntua-consumer/ui/(.*)
    rewriteTarget: /$1
    clusterIssuer: letsencrypt
    ingressClass: public

ids:
  info:
    idsid: urn:ids:enershare:connectors:NTUA:Consumer
    curator: urn:ids:enershare:participants:NTUA
    maintainer: urn:ids:enershare:participants:NTUA
    titles:
      - NTUA Meter Consumer Example@en
    descriptions:
      - NTUA Meter Consumer Example@en
    accessUrl:
      - https://{{ .Values.host }}/ntua-consumer/router  
  security:
    apiKeys:
      - id: default
        key: APIKEY-sgqgCPJWgQjmMWrKLAmkETDE
        roles:
          - DATA_APP
          - PEF_MANAGER
    users:
      - id: admin
        # -- BCrypt encoded password (defaults to enershare)
        password: $2a$12$cOEhv/gcpyCFs5KkObTbweQ0axqwIuKysZdeJMArNxHCXWzYayddu
        roles:
          - ADMIN

  daps:
    url: https://daps.enershare.dataspac.es/v2

  broker:
    id: urn:ids:enershare:connectors:MetadataBroker
    address: https://broker.enershare.dataspac.es/infrastructure
    autoRegister: true

  routes:
    ingress:
      http:
        - dataApp: http://{{ template "tsg-connector.fullname" . }}-openapi-data-app-http:8080/router
          endpoint: router
          parameters: "&matchOnUriPrefix=true"

containers:
  - type: data-app
    name: openapi-data-app
    image: docker.nexus.dataspac.es/data-apps/openapi-data-app:2.3.0
    apiKey: APIKEY-sgqgCPJWgQjmMWrKLAmkETDE
    config:
      openApi:
        usePolicyEnforcement: false
        agents:
          - id: urn:ids:enershare:connectors:NTUA:Consumer:ConsumerAgent
            backEndUrlMapping:
              0.5: http://enershare.epu.ntua.gr:8886
            title: Swagger API
            openApiBaseUrl: https://app.swaggerhub.com/apiproxy/registry/enershare_ntua/enershare-postgREST/
            versions:
            - 0.5
    services:
      - port: 8080
        name: http
        ingress:
          path: /consumer-data-app/(.*)
          rewriteTarget: /$1
          clusterIssuer: letsencrypt
          ingressClass: public
